package com.tam.model;

// Generated Apr 26, 2015 5:10:28 PM by Hibernate Tools 4.0.0

import java.util.*;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

import org.hibernate.annotations.CreationTimestamp;

/**
 * Segment generated by hbm2java
 */
@Entity
@Table(name = "segment", catalog = "tam", uniqueConstraints = @UniqueConstraint(columnNames = {
        "flt_no", "dep_date", "aa_code", "dep_port", "arr_port"}))
public class Segment implements java.io.Serializable {
    private static final long serialVersionUID = 1L;

    private Integer id;
    private Port portByArrPort = new Port();
    private Port portByDepPort = new Port();
    private String aaCode;
    private String fltNo;
    private Date depDate;
    private Date recordDate;
    private Set<Coupon> coupons = new HashSet<Coupon>(0);
    private List<Seat> seats = new ArrayList<>();

    public Segment() {
    }

    public Segment(Port portByArrPort, Port portByDepPort, String aaCode,
                   String fltNo, Date depDate, Date recordDate) {
        this.portByArrPort = portByArrPort;
        this.portByDepPort = portByDepPort;
        this.aaCode = aaCode;
        this.fltNo = fltNo;
        this.depDate = depDate;
        this.recordDate = recordDate;
    }

    public Segment(Port portByArrPort, Port portByDepPort, String aaCode,
                   String fltNo, Date depDate, Date recordDate, Set<Coupon> coupons) {
        this.portByArrPort = portByArrPort;
        this.portByDepPort = portByDepPort;
        this.aaCode = aaCode;
        this.fltNo = fltNo;
        this.depDate = depDate;
        this.recordDate = recordDate;
        this.coupons = coupons;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "arr_port", nullable = false)
    public Port getPortByArrPort() {
        return this.portByArrPort;
    }

    public void setPortByArrPort(Port portByArrPort) {
        this.portByArrPort = portByArrPort;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "dep_port", nullable = false)
    public Port getPortByDepPort() {
        return this.portByDepPort;
    }

    public void setPortByDepPort(Port portByDepPort) {
        this.portByDepPort = portByDepPort;
    }

    @Column(name = "aa_code", nullable = false, length = 3)
    public String getAaCode() {
        return this.aaCode;
    }

    public void setAaCode(String aaCode) {
        this.aaCode = aaCode;
    }

    @Column(name = "flt_no", nullable = false, length = 4)
    public String getFltNo() {
        return this.fltNo;
    }

    public void setFltNo(String fltNo) {
        this.fltNo = fltNo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "dep_date", nullable = false, length = 19)
    public Date getDepDate() {
        return this.depDate;
    }

    public void setDepDate(Date depDate) {
        this.depDate = depDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "record_date", nullable = false, length = 19)
    @CreationTimestamp
    public Date getRecordDate() {
        return this.recordDate;
    }

    public void setRecordDate(Date recordDate) {
        this.recordDate = recordDate;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "segment")
    public Set<Coupon> getCoupons() {
        return this.coupons;
    }

    public void setCoupons(Set<Coupon> coupons) {
        this.coupons = coupons;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "segment")
    public List<Seat> getSeats() {
        return seats;
    }

    public void setSeats(List<Seat> seats) {
        this.seats = seats;
    }

    public void addSeat(Seat seat) {
        if (seats == null) {
            seats = new ArrayList<>();
        }
        seats.add(seat);
        seat.setSegment(this);
    }

    @Override
    public String toString() {
        return
                "DepPort= " + portByDepPort.getCode() + '\n' +
                        "ArrPort= " + portByArrPort.getCode();
    }
}
